server:
   port: 8889

spring:
   cloud:
      config:
         server:
            git:
               uri: https://github.com/JiaoJianbo/springcloud-tutorial
               searchPaths: config-files
               username: 
               password: 
         label: master
   application:
      name: cloud-config-server

# 注册到eureka server
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
