server:
   port: 8888

spring:
   cloud:
      config:
         server:
            git:
# 使用过程中要能访问该github地址，也可以使用本地路径，如 file:///D:/dev/config-repo
               uri: https://github.com/JiaoJianbo/springcloud-tutorial/
               force-pull: true
               deleteUntrackedBranches: true
               searchPaths: config-files
               username: 
               password: 
         label: master
   application:
      name: cloud-config-server

# 注册到eureka server
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka

# Refer to: http://www.cnblogs.com/ityouknow/p/6906917.html
management:
   security:
      enabled: false

