server:
   port: 8765

spring:
   application:
      name: feign-service
   
# eureka server
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
# 开启健康检查(需要spring-boot-starter-actuator依赖)
      healthcheck:
         enabled: true

# 使用Apache HttpClient替换Feign原生httpclient
feign: 
   httpclient:
      enable: true
# 启用断路器
   hystrix:
      enabled: true

