server:
   port: 8767
 
spring:
   application:
      name: zuul-service
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
         
zuul:
   routes:
# api-1, api-2 ... 這個名字隨意
      api-1:
         path: /api-ribbon/**
         serviceId: ribbon-service
      api-2:
         path: /api-feign/**
         serviceId: feign-service
